In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
arr=[1,2,3,4,5]

In [4]:
print(arr)
type(arr)

[1, 2, 3, 4, 5]


list

In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
b.shape

(3, 3)

In [8]:
b.dtype

dtype('int32')

In [9]:
print(type(b))

<class 'numpy.ndarray'>


In [10]:
list1=[i for i in range(10)]
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
list2=[i+2 for i in range(10)]
print(list2)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [12]:
sqr=[i**2 for i in range(10)]
print(sqr)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
c=range(10000)
%timeit [i**3 for i in c]

7.99 ms ± 114 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

51.5 µs ± 520 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]


In [17]:
%timeit list(map(lambda x, y: x*y, l1, l2))

2.69 ms ± 82 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
a1 = np.array(l1)
b1 = np.array(l2)

In [19]:
%timeit a1*b1

15.4 µs ± 90.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Creating Numpy array

There are multiple ways to create numpy array. Lets walk over them

In [20]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1, 100, 7)

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [24]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.arange(500, 100, -100)

array([500, 400, 300, 200])

In [26]:
np.zeros((3,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.zeros(1, dtype=np.int32)

array([0])

In [28]:
np.zeros((1, 1), dtype=np.int32)

array([[0]])

In [29]:
a = np.array([[2, 3], [2, 4], [8, 9]])
a

array([[2, 3],
       [2, 4],
       [8, 9]])

In [30]:
a.shape

(3, 2)

In [31]:
np.zeros_like(a)


array([[0, 0],
       [0, 0],
       [0, 0]])

In [32]:
np.ones((5,2), dtype=np.int32)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [33]:
np.eye(1, dtype=np.int32)
[1]

[1]

In [34]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.full((5, 3), 3.3)

array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [36]:
np.full((5, 3), 3.3, dtype=np.int32)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [37]:
np.diag([2, 5, 68, 78])

array([[ 2,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 68,  0],
       [ 0,  0,  0, 78]])

In [38]:
x = np.diag(np.arange(1, 101))
x

array([[  1,   0,   0, ...,   0,   0,   0],
       [  0,   2,   0, ...,   0,   0,   0],
       [  0,   0,   3, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,  98,   0,   0],
       [  0,   0,   0, ...,   0,  99,   0],
       [  0,   0,   0, ...,   0,   0, 100]])

In [39]:
v = np.array([1,2,3])
print(v)
np.tile(v,(5, 2)) # stack 3 copies of v on top of each other

[1 2 3]


array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [40]:
x1 = np.array([[1, 2, 3, 4], [5, 6, 7,8 ]])
np.tile(x1, (5, 2))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8],
       [1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8],
       [1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8],
       [1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8],
       [1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [41]:
np.random.seed(53833)#random state
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.019703956740039552
0.3210059265730163
0.5240905815505337
0.41659380156268544
0.7566766565621124
0.6196223279710559


In [42]:
x = np.random.random((4, 4))
x

array([[0.9470554 , 0.76129065, 0.97161944, 0.58074448],
       [0.45624818, 0.1677047 , 0.9837774 , 0.00589398],
       [0.9823713 , 0.90390029, 0.43970885, 0.86288897],
       [0.00430195, 0.40301973, 0.98285594, 0.15724152]])

In [43]:
rounded = np.round(x, 2)
rounded

array([[0.95, 0.76, 0.97, 0.58],
       [0.46, 0.17, 0.98, 0.01],
       [0.98, 0.9 , 0.44, 0.86],
       [0.  , 0.4 , 0.98, 0.16]])

In [44]:
new = rounded * 100
new

array([[95., 76., 97., 58.],
       [46., 17., 98.,  1.],
       [98., 90., 44., 86.],
       [ 0., 40., 98., 16.]])

In [45]:
intt = new.astype(np.int32)
intt

array([[95, 76, 97, 57],
       [46, 17, 98,  1],
       [98, 90, 44, 86],
       [ 0, 40, 98, 16]])

In [46]:
intt.astype(np.float32)

array([[95., 76., 97., 57.],
       [46., 17., 98.,  1.],
       [98., 90., 44., 86.],
       [ 0., 40., 98., 16.]], dtype=float32)

In [47]:
a = np.arange(10)
a.dtype


dtype('int32')

In [48]:
#memory used by each array element in bytes
a.itemsize

4

In [49]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
x.reshape(-1, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [51]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
z.shape

(3, 4)

In [52]:
#  -1 is an unknown dimension to be figured out by numpy
z.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
# New shape as (-1, 2). row unknown, column 2. 
z.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [54]:
# New shape (2, -1). Row 2, column unknown. 
z.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [55]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# accessing Numpy array element

In [57]:
a = np.array([2,4,6,8,10,12,14,16])

In [58]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [59]:
a[2]

6

In [60]:
a[[2,6,5]]

array([ 6, 14, 12])

In [61]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [62]:
a[2:5]

array([ 6,  8, 10])

In [63]:
a[0::2]

array([ 2,  6, 10, 14])

#Lets check the same for 2 D array

In [64]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [65]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a[2,2]

9

In [67]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [68]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
a[(a > 2) & (a < 5)]

array([3, 4])

subset of numpy array

In [70]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
b[0] = 11

In [73]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [74]:
# Notice a is also changed
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [75]:
np.shares_memory(a,b)

True

In [76]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
b = a.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
b[0] = 11
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [79]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.shares_memory(a,b)

False

# More operations

In [81]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [83]:
b = np.array([[7,8,9],[10,11,12]])

In [84]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [86]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#Mathmatical operation

In [88]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [90]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [91]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [92]:
np.sum(a)

45

In [93]:
np.median(a)

5.0

In [94]:
a.std()

2.581988897471611

In [95]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.linalg.det(a)

6.66133814775094e-16

In [97]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [98]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [99]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
b = a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [101]:
np.dot(a,b)


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [102]:
a = np.array([1,1,0], dtype = bool)
a
b = np.array([1,0,1], dtype = bool)
b


array([ True, False,  True])

In [103]:
np.logical_or(a,b)

array([ True,  True,  True])

In [104]:
np.logical_and(a,b)

array([ True, False, False])

In [105]:
np.all(a == a)

True

In [106]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [107]:
a.sum()

10

In [108]:
a.sum(axis=0)

array([4, 6])

In [109]:
a.sum(axis=1)

array([3, 7])

In [110]:
a.max()

4

In [111]:
a.argmax()

3

In [112]:
a

array([[1, 2],
       [3, 4]])

In [113]:
a.shape

(2, 2)

In [114]:
a[:,np.newaxis].shape # adds a new axis -> 2D
a

array([[1, 2],
       [3, 4]])

In [115]:
np.sort(a)

array([[1, 2],
       [3, 4]])

In [116]:
np.argsort(a)

array([[0, 1],
       [0, 1]], dtype=int64)

In [117]:
a

array([[1, 2],
       [3, 4]])

In [118]:
tf = a == 5

In [119]:
tf

array([[False, False],
       [False, False]])